//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalPropertyManager.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder class.
    internal partial class Resources
    {
        private static global::System.Resources.ResourceManager? _resourceManager;

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                {
                    var temp = new global::System.Resources.ResourceManager(
                        "PersonalPropertyManager.Properties.Resources",
                        typeof(Resources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }

        internal static global::System.Globalization.CultureInfo? Culture { get; set; }

        // No public string resources registered yet.
    }
}
