//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalPropertyManager.Properties
{
    internal partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings? _defaultInstance;

        public static Settings Default
        {
            get
            {
                Settings? settings = _defaultInstance;
                if (settings == null)
                {
                    settings = new Settings();
                    _defaultInstance = settings;
                }
                return settings;
            }
        }
    }
}
